import { describe, it, expect } from "vitest";
import { M2ZnRing } from "../Ring";
import { idealGeneratedBy, isIdeal } from "../Ideal";

describe("Two-sided ideals in M2(Z2) (tiny sanity)", () => {
  const R = M2ZnRing(2);
  const Iden = {a:1,b:0,c:0,d:1};
  const Zero = {a:0,b:0,c:0,d:0};

  it("Ideal generated by identity is whole ring; by zero is {0}", () => {
    const J = idealGeneratedBy(R, [Iden]);
    expect(J.elems.length).toBe(R.elems.length);
    expect(isIdeal(J)).toBe(true);

    const K = idealGeneratedBy(R, [Zero]);
    expect(K.elems.length).toBe(1);
    expect(isIdeal(K)).toBe(true);
  });
});